/**
 * EditorSceneLoader
 *
 * Loads and manages scenes generated by Phaser Editor 2D
 * This bridges the gap between editor-generated code and your game
 */

import Phaser from 'phaser';

export class EditorSceneLoader {
  private scene: Phaser.Scene;

  constructor(scene: Phaser.Scene) {
    this.scene = scene;
  }

  /**
   * Load asset packs generated by Phaser Editor
   */
  loadAssetPacks(packKeys: string[]) {
    packKeys.forEach(key => {
      const packPath = `/assets/asset-packs/${key}.json`;
      this.scene.load.pack(key, packPath);
    });
  }

  /**
   * Launch a UI scene generated by Phaser Editor
   * Returns the scene instance for accessing its elements
   */
  launchUIScene<T extends Phaser.Scene>(sceneKey: string): T {
    this.scene.scene.launch(sceneKey);
    return this.scene.scene.get(sceneKey) as T;
  }

  /**
   * Get reference to an already running editor scene
   */
  getEditorScene<T extends Phaser.Scene>(sceneKey: string): T {
    return this.scene.scene.get(sceneKey) as T;
  }
}
