name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, develop, dev ]

permissions:
  contents: read

jobs:
  test-build:
    name: Lint • Typecheck • Test • Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wordwyrm_ci
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/wordwyrm_ci?schema=public
      NEXT_TELEMETRY_DISABLED: 1
      PRISMA_HIDE_UPDATE_MESSAGE: 1
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Prisma • validate & generate client
        run: |
          npx prisma validate
          npx prisma generate

      - name: Apply migrations to CI DB
        run: npx prisma migrate deploy

      - name: Lint
        run: npm run lint --if-present

      - name: Typecheck
        run: npm run typecheck --if-present

      - name: Test (Vitest)
        run: npm test --if-present

      - name: Build (Next.js)
        run: npm run build
